company:
  name: tom microservice
  site: hyperping.io
  link: https://hyperping.io
  logo: https://hyperping.io/assets/signallogo3.svg
  email: hello@hyperping.io
  copyright: Copyright © 2018 Hyperping. All rights reserved.

email:
  transporter:
    host: smtp.ethereal.email
    port: 587
    secure: false

  theme: salted
  template:
    welcome:
      subject: "[{company.site}] Welcome to hyperping.io!"
      from: "{company.email}"
      bcc: "{company.email}"
      body:
        greeting: Hello {props.username}
        intro: Welcome to {company.site}! We're very excited to have you on board.
        action:
          instructions: 'To get started with {company.site}, please click here:'
          button:
            color: "#22BC66"
            text: Confirm your account
            link: https://hyperping.io/confirm?s=d9729feb74992cc3482b350163a1a010

    reset:
      subject: "[{company.site}] Password Reset"
      from: "{company.email}"
      bcc: "{company.email}"
      body:
        greeting: Hello {props.username}
        intro: You have received this email because a password reset request for your account was received.
        goToAction: # Gmail feature https://developers.google.com/gmail/markup/reference/go-to-action
            text: 'Go to Dashboard'
            link: 'https://mailgen.com/confirm?s=d9729feb74992cc3482b350163a1a010'
            description: 'Check the status of your order in your dashboard'
        action:
          instructions: "Click the button below to reset your password:"
          button:
            color: '#DC4D2F'
            text: 'Reset your password'
            link: 'https://hyperping.io/creset?s=d9729feb74992cc3482b350163a1a010'
        outro: 'If you did not request a password reset, no further action is required on your part.'

    site_up:
      subject: "[{company.site}] UPTIME for {props.domain} 👍"
      from: "{company.email}"
      bcc: "{company.email}"
      body:
        greeting: Hello {props.username}
        intro: The last ping execution finished successfully
        dictionary:
          domain: "{props.domain}"
          date: Tue, 10 Jul 2018 22:10:06 UTC
          downtime: 6 min
        goToAction: # Gmail feature https://developers.google.com/gmail/markup/reference/go-to-action
            text: 'Go to Dashboard'
            link: 'https://mailgen.com/confirm?s=d9729feb74992cc3482b350163a1a010'
            description: 'Check the status of your order in your dashboard'
        action:
          instructions: "Click the button below to see more details"
          button:
            color: '#22BC66'
            text: 'See more details'
            link: ' https://hyperping.io/2734'

    site_down:
      subject: "[{company.site}] DOWNTIME for {props.domain} 👎"
      from: "{company.email}"
      bcc: "{company.email}"
      body:
        greeting: Hello {props.username}
        intro: The last ping execution failed
        dictionary:
          domain: "{props.domain}"
          date: Tue, 10 Jul 2018 22:10:06 UTC
          downtime: 6 min
        goToAction: # Gmail feature https://developers.google.com/gmail/markup/reference/go-to-action
            text: 'Go to Dashboard'
            link: 'https://mailgen.com/confirm?s=d9729feb74992cc3482b350163a1a010'
            description: 'Check the status of your order in your dashboard'
        action:
          instructions: "Click the button below to see more details"
          button:
            color: '#22BC66'
            text: 'See more details'
            link: ' https://hyperping.io/2734'

    summary:
      subject: "[{company.site}] Weekly Report"
      from: "{company.email}"
      bcc: "{company.email}"
      body:
        greeting: Hello {props.username}
        intro: Here is your weekly report of the last week
        table:
          data:
            - domain: api.microlink.io
              uptime: 99.40%
              apdex: "0.90"
              latency: 400ms
              threshold: 500ms
            - domain: api.microlink.io
              uptime: 99.40%
              apdex: "0.90"
              latency: 400ms
              threshold: 500ms
            - domain: api.microlink.io
              uptime: 99.40%
              apdex: "0.90"
              latency: 400ms
              threshold: 500ms
          columns:
            customWidth:
              item: 20%
              price: 15%
            customAlignment:
              price: right
        goToAction: # Gmail feature https://developers.google.com/gmail/markup/reference/go-to-action
            text: 'Go to Dashboard'
            link: 'https://mailgen.com/confirm?s=d9729feb74992cc3482b350163a1a010'
            description: 'Check the status of your order in your dashboard'
        action:
          instructions: "Click the button below to see more details"
          button:
            color: '#22BC66'
            text: 'See more details'
            link: ' https://hyperping.io/2734'
